# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2019 - 2021 Gemeente Amsterdam
# Generated by Django 2.1.7 on 2019-05-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0046_auto_20190503_1053'),
        ('signals', '0047_new_history_db_view'),
    ]

    operations = [
    ]
