# SPDX-License-Identifier: MPL-2.0
# Copyright (C)  - 2021 Gemeente Amsterdam
# Generated by Django 2.1.7 on 2019-05-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0049_merge_20190506_0911'),
        ('signals', '0049_SIG1203'),
    ]

    operations = [
    ]
