# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.18 on 2023-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0187_auto_20230320_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='configuration',
            field=models.JSONField(null=True),
        ),
    ]
