# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.18 on 2023-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0188_category_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='target_api',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('sigmax', 'Sigmax (City Control)'),
                                       ('gisib', 'GISIB')
                                   ],
                                   max_length=250,
                                   null=True),
        ),
    ]
