# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.18 on 2023-04-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0189_auto_20230407_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('state', models.CharField(
                    choices=[
                        ('m', 'Gemeld'),
                        ('i', 'In afwachting van behandeling'),
                        ('b', 'In behandeling'),
                        ('h', 'On hold'),
                        ('ingepland', 'Ingepland'),
                        ('ready to send', 'Extern: te verzenden'),
                        ('o', 'Afgehandeld'),
                        ('a', 'Geannuleerd'),
                        ('reopened', 'Heropend'),
                        ('s', 'Gesplitst'),
                        ('closure requested', 'Extern: verzoek tot afhandeling'),
                        ('reaction requested', 'Reactie gevraagd'),
                        ('reaction received', 'Reactie ontvangen'),
                        ('forward to external', 'Doorgezet naar extern'),
                        ('sent', 'Extern: verzonden'),
                        ('send failed', 'Extern: mislukt'),
                        ('done external', 'Extern: afgehandeld'),
                        ('reopen requested', 'Verzoek tot heropenen'),
                    ],
                    max_length=50
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusMessageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.category')),
                ('status_message', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='signals.statusmessage'
                )),
            ],
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='categories',
            field=models.ManyToManyField(through='signals.StatusMessageCategory', to='signals.Category'),
        ),
        migrations.AddConstraint(
            model_name='statusmessagecategory',
            constraint=models.UniqueConstraint(
                fields=('status_message', 'category'),
                name='signals_statusmessagecategory_unique_constraint'
            ),
        ),
        migrations.AlterModelOptions(
            name='statusmessage',
            options={
                'permissions': (('sia_statusmessagetemplate_write', 'Wijzingen van standaardteksten'),),
                'verbose_name': 'Standaardtekst',
                'verbose_name_plural': 'Standaardteksten'
            },
        ),
        migrations.AlterModelOptions(
            name='statusmessagecategory',
            options={'permissions': (('sia_statusmessagetemplate_write', 'Wijzingen van standaardteksten'),)},
        ),
    ]
