# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.18 on 2023-04-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0190_auto_20230417_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusmessagecategory',
            options={
                'permissions': (('sia_statusmessagecategory_write', 'Toewijzen van standaardteksten aan categorieën'),),
                'verbose_name': 'Standaardtekst categorietoewijzing',
                'verbose_name_plural': 'Standaardtekst categorietoewijzingen'
            },
        ),
    ]
