# Generated by Django 3.2.19 on 2023-06-19 12:51

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0191_alter_statusmessagecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
