# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.20 on 2023-08-21 08:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0193_auto_20230714_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='caption',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
