# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam

# Generated by Django 3.2.22 on 2023-10-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0196_fix_signals_celery_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={
                'ordering': (
                    'created_at',
                ),
                'permissions': [
                    ('sia_add_attachment',
                     'Kan bijlage bij een melding toevoegen.'),
                    ('sia_change_attachment',
                     'Kan gegevens van een bijlage bewerken.'),
                    ('sia_delete_attachment_of_normal_signal',
                     'Kan bijlage bij standaard melding verwijderen.'),
                    ('sia_delete_attachment_of_parent_signal',
                     'Kan bijlage bij hoofdmelding verwijderen.'),
                    ('sia_delete_attachment_of_child_signal',
                     'Kan bijlage bij deelmelding verwijderen.'),
                    ('sia_delete_attachment_of_other_user',
                     'Kan bijlage bij melding van andere gebruiker verwijderen.'),
                    ('sia_delete_attachment_of_anonymous_user',
                     'Kan bijlage toegevoegd door melder verwijderen.')
                ]
            },
        ),
    ]
