# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2025 Gemeente Amsterdam
# Generated by Django 4.2.20 on 2025-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0197_auto_20231030_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={
                'ordering': ('created_at',),
                'permissions': [
                    ('sia_add_attachment', 'Kan bijlage aan een melding toevoegen.'),
                    ('sia_change_attachment', 'Kan gegevens van een bijlage bewerken.'),
                    ('sia_delete_attachment_of_normal_signal', 'Kan bijlage bij standaard melding verwijderen.'),
                    ('sia_delete_attachment_of_parent_signal', 'Kan bijlage bij hoofdmelding verwijderen.'),
                    ('sia_delete_attachment_of_child_signal', 'Kan bijlage bij deelmelding verwijderen.'),
                    (
                        'sia_delete_attachment_of_other_user',
                        'Kan bijlage bij melding van andere gebruiker verwijderen.'
                    ),
                    ('sia_delete_attachment_of_anonymous_user', 'Kan bijlage toegevoegd door melder verwijderen.')
                ]
            },
        ),
        migrations.AlterModelOptions(
            name='reporter',
            options={
                'ordering': ('created_at',),
                'permissions': (
                    ('sia_can_view_contact_details', 'Inzien van contactgegevens melder (in melding)'),
                )
            },
        ),
        migrations.AlterField(
            model_name='signaldepartments',
            name='departments',
            field=models.ManyToManyField(related_name='+', to='signals.department'),
        ),
    ]
