# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2025 Gemeente Amsterdam
# Generated by Django 4.2.20 on 2025-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0198_alter_attachment_options_alter_reporter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(editable=False, max_length=7, null=True),
        ),
    ]
