# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2025 Gemeente Amsterdam
# Generated by Django 4.2.20 on 2025-03-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0199_location_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatype',
            options={
                'ordering': ['code'],
                'permissions': (('sia_areatype_write', 'Kan gebiedstypen schrijven.'),),
                'verbose_name': 'Gebiedstype',
                'verbose_name_plural': 'Gebiedstypen'
            },
        ),
    ]
