version: "3.9"

services:
  api:
    build:
      context: .
      target: test
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - docker-compose/environments/.test

  database:
    # postgis 3.2 is the extension version provided by Azure Database for PostgreSQL Flexible Server at the time of writing
    # https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions#postgres-12-extensions
    image: postgis/postgis:12-3.2-alpine
    shm_size: '1024m'
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: signals
      POSTGRES_USER: signals
      POSTGRES_PASSWORD: insecure
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U signals -d signals'" ]
      interval: 10s
      timeout: 5s
      retries: 5
