# Generated by Django 4.2.17 on 2025-03-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0197_auto_20231030_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_signal', to='signals.signal')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_signal', to='signals.signal')),
            ],
        ),
    ]
