# Generated by Django 4.2.17 on 2025-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('source', 'target')},
        ),
    ]
