# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.18 on 2023-03-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0187_auto_20230320_1441'),
        ('users', '0009_auto_20221018_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(related_name='user_profiles', to='signals.Department'),
        ),
    ]
