# Generated by Django 2.1.7 on 2019-04-09 13:17

from django.db import migrations

_ANSWERS = [
    # Satisfied reporters
    ('Mijn melding is snel opgepakt', True),
    ('Het probleem is verholpen', True),
    ('De gemeente heeft mijn melding goed opgepakt', True),
    ('De communicatie over de behandeling van mijn melding ging goed', True),

    # Unhappy reporters
    ('De oplossing volstaat niet, mijn melding is niet opgelost', False),
    ('Ik heb onvoldoende / onjuiste informatie gekregen', False),
    ('Er is niets met mijn melding gedaan', False),
    ('Ik voel mij niet serieus genomen door de gemeente', False),
    ('Het contact over de afhandeling was slecht', False),
    ('De behandeling duurde te lang', False),
]


def add_standard_answers(apps, schema_editor):
    StandardAnswer = apps.get_model('feedback', 'StandardAnswer')

    for answer, is_satisfied in _ANSWERS:
        StandardAnswer.objects.create(
            is_visible=True,
            is_satisfied=is_satisfied,
            text=answer,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_standard_answers),
    ]
