# Generated by Django 2.1.7 on 2019-06-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_kto_test_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardanswer',
            options={
                'verbose_name': 'Standaard antwoord',
                'verbose_name_plural': 'Standaard antwoorden'
            },
        ),
    ]
