# Generated by Django 2.1.9 on 2019-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20190605_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardanswer',
            name='reopens_when_unhappy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='standardanswer',
            name='text',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
