# Generated by Django 2.1 on 2018-08-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_longer_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='target_api',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
