# Generated by Django 2.1 on 2018-09-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_auto_20180820_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': 'datetime', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='location',
            name='_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='locations',
                                    to='signals.Signal'),
        ),
        migrations.AlterField(
            model_name='status',
            name='_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='statuses',
                                    to='signals.Signal'),
        ),
    ]
