# Generated by Django 2.1 on 2018-09-10 12:06

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def migrate_date_fields(apps, schema_editor):
    """
    Data migration for `created_at` and `updated_at` fields on models that had this fields
    implemented with `null=True`..
    """
    Signal = apps.get_model('signals', 'Signal')
    for signal in Signal.objects.all():
        if not signal.created_at:
            signal.created_at = timezone.now()
        if not signal.updated_at:
            signal.updated_at = timezone.now()
        signal.save()

    Status = apps.get_model('signals', 'Status')
    for status in Status.objects.all():
        if not status.created_at:
            status.created_at = timezone.now()
        if not status.updated_at:
            status.updated_at = timezone.now()
        status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_auto_20180905_1620'),
    ]

    operations = [
        migrations.RunPython(migrate_date_fields),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')],
                                              default='normal', max_length=10)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='priority',
            name='_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='priorities', to='signals.Signal'),
        ),
    ]
