# Generated by Django 2.1 on 2018-09-13 06:48

from django.db import migrations


def create_priority_for_existing_signals(apps, schema_editor):
    """
    Creating `Priority` objects for all `Signal` objects that don't have a priority set.
    """
    Signal = apps.get_model('signals', 'Signal')
    Priority = apps.get_model('signals', 'Priority')
    for signal in Signal.objects.all():
        if not signal.priority:
            Priority.objects.create(_signal=signal)  # Creating `Normal` priority object.


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006b_hotfix'),
    ]

    operations = [
        migrations.RunPython(create_priority_for_existing_signals),
    ]
