# Generated by Django 2.1 on 2018-09-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_auto_20180918_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='category',
            new_name='category_assignment',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryAssignment',
        ),
    ]
