# Generated by Django 2.1 on 2018-09-25 14:21

from django.db import migrations


def migrate_old_category_permissions(apps, schema_editor):
    """Migrate old permission `add_category` to new name `add_categoryassignment."""
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    CategoryAssignment = apps.get_model('signals', 'CategoryAssignment')

    ca_content_type = ContentType.objects.get_for_model(CategoryAssignment)
    add_category, _ = Permission.objects.get_or_create(codename='add_category',
                                                       content_type=ca_content_type)
    change_category, _ = Permission.objects.get_or_create(codename='change_category',
                                                          content_type=ca_content_type)
    delete_category, _ = Permission.objects.get_or_create(codename='delete_category',
                                                          content_type=ca_content_type)
    view_category, _ = Permission.objects.get_or_create(codename='view_category',
                                                        content_type=ca_content_type)

    add_categoryassignment, _ = Permission.objects.get_or_create(
        codename='add_categoryassignment',
        name='Can add category assignment',
        content_type=ca_content_type)

    # Re-assign permission `add_category_assigment` to existing groups.
    for group in Group.objects.all():
        if add_category in group.permissions.all():
            group.permissions.add(add_categoryassignment)

    # Removing obsolete permission objects.
    add_category.delete()
    change_category.delete()
    delete_category.delete()
    view_category.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_auto_20180918_1551'),
    ]

    operations = [
        migrations.RunPython(migrate_old_category_permissions),
    ]
