# Generated by Django 2.1 on 2018-09-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_auto_20180918_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='category',
            new_name='category_assignment',
        ),
        migrations.AlterField(
            model_name='categoryassignment',
            name='_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='category_assignments',
                                    to='signals.Signal'),
        ),
        migrations.AlterField(
            model_name='categoryassignment',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='category_assignments',
                                    to='signals.SubCategory'),
        ),
    ]
