# Generated by Django 2.1.1 on 2018-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0015_auto_20180927_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
