# Generated by Django 2.1 on 2018-10-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0020_auto_20181015_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={
                'get_latest_by': 'datetime',
                'ordering': ('created_at',),
                'permissions': (
                    ('push_to_sigmax', 'Push to Sigmax/CityControl'),
                ),
                'verbose_name_plural': 'Statuses'
            },
        ),
    ]
