# Generated by Django 2.1.2 on 2018-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0023_subcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryassignment',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
