# Generated by Django 2.1.2 on 2018-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0023_subcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='zaak_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
