# Generated by Django 2.1.2 on 2018-10-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0024_signal_zaak_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='zaak_identificatie',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='zaak_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
