# Generated by Django 2.1.2 on 2018-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0025_create_history_view_in_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('when', models.DateTimeField(null=True)),
                ('what', models.CharField(max_length=255)),
                ('who', models.CharField(max_length=255, null=True)),
                ('extra', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'db_table': 'signals_history_view',
                'managed': False,
            },
        ),
    ]
