# Generated by Django 2.1.2 on 2018-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0025_auto_20181026_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
