# Generated by Django 2.1.2 on 2018-11-29 07:45

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0026_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryassignment',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='category_assignments', to='signals.MainCategory'),
        ),
        migrations.AlterField(
            model_name='categoryassignment',
            name='extra_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryassignment',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='category_assignments', to='signals.SubCategory'),
        ),
    ]
