# Generated by Django 2.1.2 on 2018-11-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0027_SIG858'),
        ('signals', '0027_auto_20181129_0845'),
    ]

    operations = [
    ]
