# Generated by Django 2.1.2 on 2019-01-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0028_auto_20181204_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={
                'ordering': ('created_at', ),
                'permissions': (
                    ('sia_read', 'Can read from SIA'),
                    ('sia_write', 'Can write to SIA')
                )
            },
        ),
    ]
