# Generated by Django 2.1.2 on 2019-01-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0028_auto_20181204_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='children', to='signals.Signal'),
        ),
    ]
