# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2019 - 2021 Gemeente Amsterdam
# Generated by Django 2.1.2 on 2019-01-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0029_signal_parent'),
        ('signals', '0029_auto_20190109_1415'),
    ]

    operations = [
    ]
