# Generated by Django 2.1.5 on 2019-02-05 10:49

from django.db import migrations
import mimetypes


def copy_images(apps, schema_editor):
    Signal = apps.get_model('signals', 'Signal')
    Attachment = apps.get_model('signals', 'Attachment')

    for signal in Signal.objects.all():
        if signal.image:
            attachment = Attachment()
            attachment.file = signal.image
            attachment._signal = signal
            attachment.is_image = True  # No extra checking

            mimetype, _ = mimetypes.guess_type(attachment.file.url)

            if mimetype is not None:
                attachment.mimetype = mimetype

            attachment.save()


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0030_attachment'),
    ]

    operations = [
        migrations.RunPython(copy_images)
    ]
