# Generated by Django 2.1.5 on 2019-02-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0031_auto_20190205_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='image',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='signals.Signal'),
        ),
    ]
