# Generated by Django 2.1.7 on 2019-02-12 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0034_auto_20190205_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ('created_at',), 'permissions': (
                ('sia_read', 'Can read from SIA'), ('sia_write', 'Can write to SIA'),
                ('sia_backoffice', 'SIA Backoffice'))},
        ),
    ]
