# Generated by Django 2.1.7 on 2019-02-12 16:23

from django.contrib.auth.management import create_permissions
from django.db import migrations


def add_backoffice_permissions(apps, schema_editor):

    # Make permissions available to migrations
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = False

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    permission = Permission.objects.get(codename='sia_backoffice')

    for group in Group.objects.all():
        group.permissions.add(permission)
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0035_auto_20190212_1722'),
    ]

    operations = [
        migrations.RunPython(add_backoffice_permissions)
    ]
