# Generated by Django 2.1.7 on 2019-03-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0035_auto_20190313_0952'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_at'], name='signals_att_created_6ac134_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['is_image'], name='signals_att_is_imag_2c4a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['_signal', 'is_image'],
                               name='signals_att__signal_89a833_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='signals_dep_name_78e3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='signals_not_created_feb36f_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['id', 'parent'], name='signals_sig_id_09cd8a_idx'),
        ),
    ]
