# Generated by Django 2.1.7 on 2019-03-14 12:59

from django.db import migrations

backup_categories = "CREATE TABLE signals_category_backup AS TABLE signals_category"
backup_main_categories = "CREATE TABLE signals_maincategory_backup AS TABLE signals_maincategory"

copy_maincategories = """
insert into signals_category(id, name, handling, slug, is_active)
select nextval('signals_subcategory_id_seq'), name, 'REST', slug, true from signals_maincategory;
"""

link_new_parent_categories = """
update signals_category as currentrow
set parent_id=newparent.id
from (
    select id, slug
    from signals_maincategory
) as main_categories
left join signals_category as newparent
on main_categories.slug = newparent.slug
where currentrow.parent_id is not null
and currentrow.parent_id = main_categories.id
;
"""


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0038_auto_20190314_1311'),
    ]

    operations = [
        migrations.RunSQL(backup_categories),
        migrations.RunSQL(backup_main_categories),
        migrations.RunSQL(copy_maincategories),
        migrations.RunSQL(link_new_parent_categories),
    ]
