# Generated by Django 2.1.7 on 2019-02-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('signals', '0038_auto_20190212_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='categories', to='auth.Permission'),
        ),
    ]
