# Generated by Django 2.1.7 on 2019-02-12 16:22

import django.db.models.deletion
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def add_category_permissions(apps, schema_editor):
    # Make permissions available to migrations
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = False

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    permission = Permission.objects.get(codename='sia_all_categories')

    for group in Group.objects.all():
        group.permissions.add(permission)
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('signals', '0039_auto_20190314_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ('created_at',), 'permissions': (
                ('sia_read', 'Can read from SIA'), ('sia_write', 'Can write to SIA'),
                ('sia_all_categories', 'Can access all categories'))},
        ),
        migrations.RunPython(add_category_permissions),
        migrations.AddField(
            model_name='category',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='categories', to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='children', to='signals.Category'),
        ),
    ]
