# Generated by Django 2.1.7 on 2019-03-21 11:26

from django.db import migrations

fix_overig_query = "update signals_category " \
                   "set parent_id=(" \
                   "    select id " \
                   "    from signals_category " \
                   "    where slug='overig' and parent_id is null" \
                   ") " \
                   "where slug='overig' and id=parent_id;"


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0039_auto_20190314_1359'),
    ]

    operations = [
        migrations.RunSQL(fix_overig_query),
    ]
