# Generated by Django 2.1.7 on 2019-03-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0040_SIG-1014'),
        ('signals', '0041_auto_20190325_1520'),
    ]

    operations = [
    ]
