# Generated by Django 2.1.7 on 2019-04-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0042_auto_new_history_db_view'),
        ('signals', '0042_merge_20190328_1512'),
    ]

    operations = [
    ]
