# Generated by Django 2.1.7 on 2019-04-17 08:58

from django.db import migrations


ADD = {
    'afval': [],
    'ondermijning': [],
    'openbaar-groen-en-water': [],
    'overig': [],
    'overlast-bedrijven-en-horeca': [],
    'overlast-in-de-openbare-ruimte': [],
    'overlast-op-het-water': [],
    'overlast-van-dieren': [],
    'overlast-van-en-door-personen-of-groepen': [],
    'wegen-verkeer-straatmeubilair': [],
}

REMOVE = {
    'afval': ['bedrijfsafval'],
    'ondermijning': [],
    'openbaar-groen-en-water': [],
    'overig': [],
    'overlast-bedrijven-en-horeca': [],
    'overlast-in-de-openbare-ruimte': [],
    'overlast-op-het-water': ['overlast-op-het-water-vaargedrag'],
    'overlast-van-dieren': [],
    'overlast-van-en-door-personen-of-groepen': [],
    'wegen-verkeer-straatmeubilair': [],
}

CHANGE = {
    'afval': {
        'overig-afval': {
            'handling': 'REST',
        }
    },
    'ondermijning': {},
    'openbaar-groen-en-water': {
        'overig-groen-en-water': {
            'handling': 'REST',
        }
    },
    'overig': {},
    'overlast-bedrijven-en-horeca': {},
    'overlast-in-de-openbare-ruimte': {},
    'overlast-op-het-water': {},
    'overlast-van-dieren': {},
    'overlast-van-en-door-personen-of-groepen': {},
    'wegen-verkeer-straatmeubilair': {},
}


def add_categories(apps, schema_editor):
    Category = apps.get_model('signals', 'Category')
    for main_slug, data in ADD.items():
        if not data:
            continue

        main_category = Category.get(slug=main_slug, parent__is_null=True)
        for new_sub_category_data in data:
            pass  # setup TBD


def remove_categories(apps, schema_editor):
    Category = apps.get_model('signals', 'Category')
    for main_slug, to_remove in REMOVE.items():
        if not to_remove:
            continue

        main_category = Category.get(slug=main_slug, parent__is_null=True)
        for sub_slug in to_remove:
            sub_category = Category.get(slug=sub_slug, parent=main_category)
            sub_category.is_active = False
            sub_category.save()


def change_categories(apps, schema_editor):
    Category = apps.get_model('signals', 'Category')
    for main_slug, data in ADD.items():
        if not data:
            continue

        main_category = Category.get(slug=main_slug, parent__is_null=True)
        for sub_slug, sub_data in data.items():
            sub_category = Category.get(slug=sub_slug, parent=main_category)

            # mutate here
            if 'handling' in sub_data:
                sub_cateory.handling = sub_data['handling']
            
            sub_category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0043_merge_20190404_0927'),
    ]

    operations = [
    ]
