# Generated by Django 2.1.7 on 2019-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0045_category_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryassignment',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
