# Generated by Django 2.1.7 on 2019-04-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0044_auto_20190418_1143'),
        ('signals', '0045_category_changes'),
    ]

    operations = [
    ]
