# Generated by Django 2.1.7 on 2019-05-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0048_merge_20190503_1542'),
        ('signals', '0046_merge_20190425_1401'),
    ]

    operations = [
    ]
