# Generated by Django 2.1.7 on 2019-05-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0048_merge_20190503_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('new_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                   related_name='+', to='signals.Category')),
                ('old_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                   related_name='+', to='signals.Category',
                                                   unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
