# Generated by Django 2.1.7 on 2019-05-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0049_auto_20190510_1453'),
        ('signals', '0049_merge_20190506_0911'),
    ]

    operations = [
    ]
