# Generated by Django 2.1.7 on 2019-05-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0050_merge_20190513_1045'),
        ('signals', '0051_auto_20190513_1537'),
    ]

    operations = [
    ]
