# Generated by Django 2.1.7 on 2019-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0056_SIG-1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='handling',
            field=models.CharField(
                choices=[
                    ('A3DMC', 'A3DMC'),
                    ('A3DEC', 'A3DEC'),
                    ('A3WMC', 'A3WMC'),
                    ('A3WEC', 'A3WEC'),
                    ('I5DMC', 'I5DMC'),
                    ('STOPEC', 'STOPEC'),
                    ('KLOKLICHTZC', 'KLOKLICHTZC'),
                    ('GLADZC', 'GLADZC'),
                    ('A3DEVOMC', 'A3DEVOMC'),
                    ('WS1EC', 'WS1EC'),
                    ('WS2EC', 'WS2EC'),
                    ('WS3EC', 'WS3EC'),
                    ('REST', 'REST'),
                    ('ONDERMIJNING', 'ONDERMIJNING'),
                    ('EMPTY', 'EMPTY'),
                    ('LIGHTING', 'LIGHTING')],
                default='REST',
                max_length=20
            ),
        ),
    ]
