# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2019 - 2021 Gemeente Amsterdam
# Generated by Django 2.1.7 on 2019-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0059_auto_20190605_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessagetemplate',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
