# Generated by Django 2.1.9 on 2019-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0064_category_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessagetemplate',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusmessagetemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
