# Generated by Django 2.1.10 on 2019-07-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0068_deparment_change'),
        ('signals', '0068_auto_20190730_1333'),
    ]

    operations = [
    ]
