# Generated by Django 2.1.10 on 2019-08-06 12:54

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0068_deparment_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredSignalFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10000)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='storedsignalfilter',
            unique_together={('name', 'created_by')},
        ),
    ]
