# Generated by Django 2.1.11 on 2019-09-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0071_auto_20190904_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedsignalfilter',
            name='refresh',
            field=models.BooleanField(default=False),
        )
    ]
