# Generated by Django 2.2.6 on 2019-10-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0077_fix_split_signals_problem'),
        ('signals', '0077_SIG-1788'),
    ]

    operations = [
    ]
