# Generated by Django 2.2.6 on 2019-11-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0080_set_slo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={
                'ordering': ('created_at',),
                'permissions': (
                    ('sia_read', 'Can read from SIA'),
                    ('sia_write', 'Can write to SIA'),
                    ('sia_split', 'Can split a signal into a parent with X children'),
                    ('sia_signal_create_initial', 'Can create new signals'),
                    ('sia_signal_create_note', 'Can create notes for signals'),
                    ('sia_signal_change_status', 'Can change the status of a signal'),
                    ('sia_signal_change_category', 'Can change the category of a signal'),
                    ('sia_signal_export', 'Can export signals'),
                    ('sia_signal_report', 'Can create reports for signals')
                )
            },
        ),
    ]
