# Generated by Django 2.2.6 on 2019-11-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0081_auto_20191101_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ('name',),
                'permissions': (
                    ('sia_can_view_all_categories', 'View all categories (this will override the category permission based on the user/department relation)'),  # noqa
                ),
                'verbose_name_plural': 'Categories'},
        ),
    ]
