# Generated by Django 2.2.6 on 2019-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0082_auto_20191113_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='extra_properties',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='remove_at',
        ),
        migrations.AddField(
            model_name='reporter',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
