# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2019 - 2021 Gemeente Amsterdam
# Generated by Django 2.2.6 on 2019-11-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0083_category_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='extra_properties',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='remove_at',
        ),
        migrations.AddField(
            model_name='reporter',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        )
    ]
