# Generated by Django 2.2.9 on 2020-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0091_unstick_signals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'permissions': (('sia_can_view_all_categories',
                                                             'View all categories (this will override the category permission based on the user/department relation)'),  # noqa
                                                            ('sia_category_read', 'Can read Categories from SIA'),
                                                            ('sia_category_write', 'Can write Categories to SIA')),
                     'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelevelobjective',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelevelobjective',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        )
    ]
