# Generated by Django 2.2.9 on 2020-01-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0092_sig-2113-sig-2152'),
        ('signals', '0092_category_changes'),
    ]

    operations = [
    ]
