# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2020 - 2021 Gemeente Amsterdam
# Generated by Django 2.2.10 on 2020-03-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0096_refactor_anonymize_reporter'),
        ('signals', '0098_sig-2193'),
    ]

    operations = [
    ]
