# Generated by Django 2.2.10 on 2020-03-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0099_added_type'),
        ('signals', '0099_merge_20200302_1417'),
    ]

    operations = [
    ]
