# Generated by Django 2.2.12 on 2020-04-21 21:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0104_auto_20200410_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='AreaHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('_tracked_pk', models.PositiveIntegerField()),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_created_by', models.EmailField(max_length=254, null=True)),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.AreaType')),
            ],
            options={
                'ordering': ['_created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.AreaType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
