# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2020 - 2021 Gemeente Amsterdam
# Generated by Django 2.2.13 on 2020-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0114_category_changes_SIG-2872'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='stadsdeel',
            field=models.CharField(choices=[
                ('A', 'Centrum'),
                ('B', 'Westpoort'),
                ('E', 'West'),
                ('M', 'Oost'),
                ('N', 'Noord'),
                ('T', 'Zuidoost'),
                ('K', 'Zuid'),
                ('F', 'Nieuw-West'),
                ('H', 'Het Amsterdamse Bos'),
                ('W', 'Weesp')
            ], max_length=1, null=True),
        ),
    ]
