# Generated by Django 2.2.13 on 2020-07-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0115_auto_20200714_1414'),
        ('signals', '0115_auto_20200709_0910'),
    ]

    operations = [
    ]
