# Generated by Django 2.2.13 on 2020-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0116_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area_code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='area_type_code',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
