# Generated by Django 2.2.13 on 2020-07-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0116_merge_20200727_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='area_type',
            new_name='area_type_code',
        ),
    ]
