# Generated by Django 2.2.13 on 2020-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0117_auto_20200729_1552'),
        ('signals', '0116_source'),
    ]

    operations = [
    ]
