# Generated by Django 2.2.13 on 2020-08-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0118_expression_expressioncontext_expressiontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expression',
            options={'permissions': (('sia_expression_read', 'Inzien van expressies'), ('sia_expression_write', 'Wijzigen van expressies')), 'verbose_name': 'Expression', 'verbose_name_plural': 'Expression'}, # noqa
        ),
    ]
