# Generated by Django 2.2.13 on 2020-09-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0118_DEELMELDINGEN_HISTORY'),
        ('signals', '0119_auto_20200819_1531'),
    ]

    operations = [
    ]
