# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2020 - 2021 Vereniging van Nederlandse Gemeenten, Gemeente Amsterdam
# Generated by Django 2.2.13 on 2020-09-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0120_department_can_direct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'ExpressionsType',
                'verbose_name_plural': 'ExpressionType',
            },
        ),
        migrations.CreateModel(
            name='ExpressionContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('identifier_type', models.CharField(
                    choices=[
                        ('point', 'point'),
                        ('str', 'str'),
                        ('number', 'number'),
                        ('time', 'time'),
                        ('set', 'set'),
                        ('dict', 'dict')
                    ],
                    default='number',
                    max_length=255
                )),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.ExpressionType')),
            ],
            options={
                'verbose_name': 'ExpressionContext',
                'verbose_name_plural': 'ExpressionContext',
            },
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.ExpressionType')),
            ],
            options={
                'verbose_name': 'Expression',
                'verbose_name_plural': 'Expression',
                'permissions': (
                    ('sia_expression_read', 'Inzien van expressies'),
                    ('sia_expression_write', 'Wijzigen van expressies')
                ),
                'unique_together': {('name', '_type')},
            },
        ),
    ]
