# Generated by Django 2.2.13 on 2020-09-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0119_rename_eigen-organisatie_to_interne-melding'),
        ('signals', '0120_merge_20200903_1303'),
    ]

    operations = [
    ]
