# Generated by Django 2.2.13 on 2020-09-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0121_signaldepartments'),
        ('users', '0007_signaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='user_assignment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SignalUser'),
        ),
        migrations.AddField(
            model_name='signaldepartments',
            name='_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_departments', to='signals.Signal'), # noqa
        ),
        migrations.AddField(
            model_name='signaldepartments',
            name='departments',
            field=models.ManyToManyField(related_name='_signaldepartments_departments_+', to='signals.Department'),
        ),
        migrations.AddField(
            model_name='signal',
            name='department_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal', to='signals.SignalDepartments'), # noqa
        ),
        migrations.AlterUniqueTogether(
            name='signaldepartments',
            unique_together={('_signal', 'relation_type')},
        ),
    ]
