# Generated by Django 2.2.13 on 2020-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0122_SLA_HISTORY'),
    ]

    operations = [
        migrations.RenameModel('DirectingDepartments', 'SignalDepartments'),
        migrations.AlterField(
            model_name='signaldepartments',
            name='_signal',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='signal_departments', to='signals.Signal'), # noqa
        ),
        migrations.AlterField(
            model_name='signal',
            name='directing_departments_assignment',
            field=models.OneToOneField(null=True, on_delete=models.deletion.SET_NULL, related_name='directing_department_signal', to='signals.SignalDepartments'), # noqa
        ),
        migrations.AddField(
            model_name='signaldepartments',
            name='relation_type',
            field=models.CharField(choices=[('directing', 'directing'), ('routing', 'routing')], default='directing', max_length=20), # noqa
        ),
    ]
