# Generated by Django 2.2.13 on 2020-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0122_SLA_HISTORY'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('directing', 'directing'), ('routing', 'routing')], default='directing', max_length=20)), # noqa
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
