# Generated by Django 2.2.13 on 2020-08-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0122_SLA_HISTORY'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('sia_questions_read', 'Inzien van additionele vragen'), ('sia_questions_write', 'Wijzigen van additionele vragen')), 'verbose_name_plural': 'Questions'}, # noqa
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
