# Generated by Django 2.2.13 on 2020-09-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0123_signaldepartments'),
        ('users', '0007_signaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaldepartments',
            name='_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_departments', to='signals.Signal'), # noqa
        ),
        migrations.AddField(
            model_name='signaldepartments',
            name='departments',
            field=models.ManyToManyField(related_name='_signaldepartments_departments_+', to='signals.Department'),
        ),
    ]
