# Generated by Django 2.2.13 on 2020-09-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0123_migrate_directing_department_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='directing_departments_assignment',
        ),
        migrations.DeleteModel(
            name='DirectingDepartments',
        ),
    ]
