# Generated by Django 2.2.13 on 2020-09-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0124_migrate_directing_department_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='directing_departments_assignment',
        ),
        migrations.DeleteModel(
            name='DirectingDepartments',
        ),
        migrations.AddField(
            model_name='signal',
            name='directing_departments_assignment',
            field=models.OneToOneField(null=True, on_delete=models.deletion.SET_NULL, related_name='directing_department_signal', to='signals.SignalDepartments'), # noqa
        ),
        migrations.AddField(
            model_name='signal',
            name='routing_assignment',
            field=models.OneToOneField(null=True, on_delete=models.deletion.SET_NULL, related_name='routing_signal', to='signals.SignalDepartments'), # noqa
        ),
        migrations.AddField(
            model_name='signal',
            name='user_assignment',
            field=models.OneToOneField(null=True, on_delete=models.deletion.SET_NULL, related_name='user_assignment_signal', to='users.SignalUser'), # noqa
        ),

    ]
