# Generated by Django 2.2.13 on 2020-09-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0121_merge_20200915_1256'),
        ('signals', '0127_routingexpression'),
    ]

    operations = [
    ]
