# Generated by Django 2.2.13 on 2020-12-14 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0130_altered_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signaluser',
            name='_signal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='signals.Signal'),
        ),
        migrations.AddField(
            model_name='signaluser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), # noqa
        ),
    ]
