# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2020 - 2021 Vereniging van Nederlandse Gemeenten, Gemeente Amsterdam
# Generated by Django 2.2.13 on 2021-03-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0134_deadlines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
    ]
