# Generated by Django 3.2.5 on 2021-08-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0143_rename__user_routingexpression_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routingexpression',
            old_name='employee',
            new_name='_user',
        ),
    ]
