# Generated by Django 3.2.5 on 2021-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0143_storedsignalfilter_show_on_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('plain_text', 'PlainText'), ('text_input', 'TextInput'), ('multi_text_input', 'MultiTextInput'), ('checkbox_input', 'CheckboxInput'), ('radio_input', 'RadioInput'), ('select_input', 'SelectInput'), ('text_area_input', 'TextareaInput'), ('map_select', 'MapSelect'), ('asset_select', 'AssetSelect')], default='plain_text', max_length=32),
        ),
    ]
