# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2021 Gemeente Amsterdam
# Generated by Django 3.2.5 on 2021-12-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0147_routingexpression__user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'permissions': (('sia_can_view_contact_details',
                                      'Inzien van contactgegevens melder (in melding)'),)},
        ),
    ]
