# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2021 Gemeente Amsterdam
# Generated by Django 3.2.10 on 2021-12-22 09:55
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_auto_20210830_2156'),
        ('signals', '0148_alter_reporter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='questionnaires.questionnaire'),
        ),
    ]
