# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Gemeente Amsterdam
# Generated by Django 3.2.12 on 2022-02-21 07:48
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0151_new_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='public_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
