# Generated by Django 3.2.12 on 2022-03-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0154_statusmessagetemplate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
