# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Gemeente Amsterdam
# Generated by Django 3.2.15 on 2022-09-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0162_signal_user_HISTORY'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='icons/categories/'),
        ),
    ]
