# Generated by Django 2.1.2 on 2018-12-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0028_auto_20181204_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityControlRoundtrip',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('_signal', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='citycontrol_roundtrips+',
                    to='signals.Signal'
                )),
            ],
        ),
    ]
