# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2025 Delta10 B.V.
# Generated by Django 4.2.21 on 2025-05-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0201_alter_area_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_state', models.CharField(choices=[('o', 'Afgehandeld'), ('a', 'Geannuleerd')], help_text='Gewenste status', max_length=20)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('expression', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signals.expression')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardToExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('expression', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signals.expression')),
            ],
        ),
    ]
