openapi: 3.0.0

info:
  title: Questionnaires private endpoints
  description: >-
    *** THIS APP IS STILL IN DEVELOPMENT, API MAY STILL CHANGE ***


    A questionnaires app for the Signals project.
    This swagger file contains all private endpoints of the app.
  contact:
    email: "datapunt@amsterdam.nl"
  version: "0.1.0-dev"

servers:
  - url: https://127.0.0.1:{port}/signals/v1
    description: Used for local development
    variables:
      port:
        enum:
          - '8000'
          - '8080'
          - '80'
        default: '8000'

  - url: /signals/v1

paths:
  /private/qa/questionnaires:
    get:
      description:
      responses:
        '200':
          description: List of Questionnaires
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateQuestionnaires'
      security:
        - OAuth2:
            - SIG/ALL

  /private/qa/questionnaires/{pk}:
    parameters:
      - name: pk
        in: path
        description: Primary key of Questionnaire
        required: true
        schema:
          type: integer
          example: 1
    get:
      responses:
        '200':
          description: Detail of the requested Questionnaire
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateQuestionnaire'
        '404':
          description: Question not found
      security:
        - OAuth2:
            - SIG/ALL

  /private/qa/questions:
    get:
      responses:
        '200':
          description: List of Questions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateQuestions'
      security:
        - OAuth2:
            - SIG/ALL

  /private/qa/questions/{pk}:
    parameters:
      - name: pk
        in: path
        description: Primary key of Questionnaire
        required: true
        schema:
          type: integer
          example: 1
    get:
      responses:
        '200':
          description: Detail of the selected Question
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateQuestion'
        '404':
          description: Question not found
      security:
        - OAuth2:
            - SIG/ALL

components:
  schemas:
    HALPaginationLinks:
      type: object
      properties:
        self:
          type: object
          properties:
            href:
              type: string
              description: URI of current page
              format: uri
        next:
          type: object
          properties:
            href:
              type: string
              description: URI of the next page
              format: uri
              nullable: true
        previous:
          type: object
          properties:
            href:
              type: string
              description: URI of the previous page
              format: uri
              nullable: true

    PrivateQuestionnaires:
      description: JSON serialization of paginated list of Questionnaires
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HALPaginationLinks'
        count:
          type: integer
          description: Total count of results for the request
          example: 50
        results:
          type: array
          description: A list of Questionnaires, paginated
          items:
            $ref: '#/components/schemas/PrivateQuestionnaire'

    PrivateQuestionnaire:
      description: Information about a Questionnaire
      type: object
      properties:
        _links:
          type: object
          properties:
            _link:
              description: HAL JSON links
              type: object
              properties:
                self:
                  type: object
                  properties:
                    href:
                      description: URI of the Questionnaire
                      type: string
                      format: uri
        _display:
          description: Display name of the Questionnaire
          type: string
        id:
          type: integer
          example: 1
        uuid:
          type: string
          pattern: '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'
          example: '00000000-0000-0000-0000-000000000000'
        name:
          type: string
          example: "Questionnaire #1"
        description:
          type: string
          nullable: true
          example: "Describing the Questionnaire"
        is_active:
          type: boolean
          example: true
        created_at:
          type: string
          example: '2021-01-01T00:00:00+00:00'
        first_question:
          $ref: '#/components/schemas/PrivateQuestion'

    PrivateQuestions:
      description: JSON serialization of paginated list of Questions
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HALPaginationLinks'
        count:
          type: integer
          description: Total count of results for the request
          example: 50
        results:
          type: array
          description: A list of Questions, paginated
          items:
            $ref: '#/components/schemas/PrivateQuestion'

    PrivateQuestion:
      type: object
      properties:
        _links:
          type: object
          properties:
            _link:
              description: HAL JSON links
              type: object
              properties:
                self:
                  type: object
                  properties:
                    href:
                      description: URI of the Question, using the KEY
                      type: string
                      format: uri
                sia:uuid-self:
                  type: object
                  properties:
                    href:
                      description: URI of the Question, using the UUID
                      type: string
                      format: uri
                sia:post-answer:
                  type: object
                  properties:
                    href:
                      description: URI where the answer can be posted
                      type: string
                      format: uri
        _display:
          description: Display name of the Question
          type: string
        id:
          type: integer
          example: 1
        key:
          type: string
          nullable: true
          example: 'a-key-describing-the-question'
        uuid:
          type: string
          pattern: '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'
          example: '00000000-0000-0000-0000-000000000000'
        label:
          type: string
          example: 'Long label for the question'
        short_label:
          type: string
          example: 'Short label'
        field_type:
          type: string
          enum:
            - 'plain_text'
            - 'integer'
          example: 'plain_text'
        next_rules:
          type: string
          nullable: true
          example: [ { 'payload': 'yes', 'ref': 'next-question-key-1' }, { 'payload': 'no', 'ref': 'next-question-key-2' } ]
        required:
          type: boolean
          example: false
        created_at:
          type: string
          example: '2021-01-01T00:00:00+00:00'

  securitySchemes:
    OAuth2:
      description: SIA API is using OAuth2 implicit grant flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: '/oauth2/authorize'
          scopes:
            SIG/ALL: General access to SIA Django application.
