# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Gemeente Amsterdam
# Generated by Django 3.2.15 on 2022-08-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_auto_20220818_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
