# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Gemeente Amsterdam
# Generated by Django 3.2.15 on 2022-08-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_question_extra_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_answers_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='additional_validation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
