# Generated by Django 2.1.2 on 2018-11-06 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0023_subcategory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaakDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                 verbose_name='ID')),
                ('drc_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ZaakSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                 verbose_name='ID')),
                ('zrc_link', models.URLField()),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='zaken', to='signals.Signal')),
            ],
        ),
        migrations.AddField(
            model_name='zaakdocument',
            name='zaak_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='documenten', to='zds.ZaakSignal'),
        ),
    ]
