# Generated by Django 2.1.2 on 2018-11-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zds', '0002_auto_20181106_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaaksignal',
            name='signal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='zaak', to='signals.Signal'),
        ),
    ]
