# Generated by Django 2.1.2 on 2018-11-06 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zds', '0003_auto_20181106_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaakdocument',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='zaaksignal',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='zaakdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaakdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zaaksignal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaaksignal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
