# Generated by Django 2.1.2 on 2018-12-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0028_auto_20181204_0915'),
        ('zds', '0004_auto_20181106_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drc_link', models.URLField(blank=True, null=True)),
                ('connected_in_external_system', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zrc_link', models.URLField(blank=True, null=True)),
                ('connected_in_external_system', models.BooleanField(blank=True, default=False)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='signals.Signal')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zrc_link', models.URLField(blank=True, null=True)),
                ('case_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusses', to='zds.CaseSignal')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='zaakdocument',
            name='zaak_signal',
        ),
        migrations.RemoveField(
            model_name='zaaksignal',
            name='signal',
        ),
        migrations.DeleteModel(
            name='ZaakDocument',
        ),
        migrations.DeleteModel(
            name='ZaakSignal',
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='zds.CaseSignal'),
        ),
    ]
