# Generated by Django 2.1.2 on 2018-12-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0028_auto_20181204_0915'),
        ('zds', '0005_auto_20181211_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesignal',
            name='sync_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_status', to='signals.Status'),
        ),
    ]
