from _typeshed import Incomplete

LOGGER: Incomplete

def parse_www_authenticate_header(header): ...
def import_from_settings(attr, *args): ...
def absolutify(request, path): ...
def is_authenticated(user): ...
def add_state_and_nonce_to_session(request, state, params) -> None: ...
