from _typeshed import Incomplete
from django.views.generic import View
from mozilla_django_oidc.utils import absolutify as absolutify, add_state_and_nonce_to_session as add_state_and_nonce_to_session, import_from_settings as import_from_settings

class OIDCAuthenticationCallbackView(View):
    http_method_names: Incomplete
    @staticmethod
    def get_settings(attr, *args): ...
    @property
    def failure_url(self): ...
    @property
    def success_url(self): ...
    def login_failure(self): ...
    def login_success(self): ...
    user: Incomplete
    def get(self, request): ...

def get_next_url(request, redirect_field_name): ...

class OIDCAuthenticationRequestView(View):
    http_method_names: Incomplete
    OIDC_OP_AUTH_ENDPOINT: Incomplete
    OIDC_RP_CLIENT_ID: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def get_settings(attr, *args): ...
    def get(self, request): ...
    def get_extra_params(self, request): ...

class OIDCLogoutView(View):
    http_method_names: Incomplete
    @staticmethod
    def get_settings(attr, *args): ...
    @property
    def redirect_url(self): ...
    def post(self, request): ...
    def get(self, request): ...
