# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.18 on 2023-03-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_add_reaction_statusses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horecacsvexport',
            name='uploaded_file',
            field=models.FileField(upload_to='exports/%Y'),
        ),
    ]
