# Generated by Django 2.0.6 on 2018-06-11 10:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buurt',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=14)),
                ('vollcode', models.CharField(max_length=4)),
                ('naam', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'buurt_simple',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(blank=True, default='', max_length=50)),
                ('sub', models.CharField(blank=True, default='', max_length=50)),
                ('priority', models.IntegerField(null=True)),
                ('ml_priority', models.IntegerField(null=True)),
                ('ml_cat', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ml_prob', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ml_cat_all', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=50), null=True, size=None)),
                ('ml_cat_all_prob', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('ml_sub_cat', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('ml_sub_prob', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('ml_sub_all', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=50), null=True, size=None)),
                ('ml_sub_all_prob', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_properties', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('stadsdeel', models.CharField(max_length=1, null=True)),
                ('buurt_code', models.CharField(max_length=4, null=True)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_properties', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('remove_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_properties', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('signal_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', models.CharField(default='api', max_length=15)),
                ('text', models.CharField(default='', max_length=1000)),
                ('text_extra', models.CharField(blank=True, default='', max_length=1000)),
                ('incident_date_start', models.DateTimeField()),
                ('incident_date_end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('operational_date', models.DateTimeField(null=True)),
                ('expire_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('upload', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='uploads/%Y/%m/%d/'), null=True, size=None)),
                ('extra_properties', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='signals.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='signals.Location')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='signals.Reporter')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=1000)),
                ('user', models.EmailField(max_length=254, null=True)),
                ('state', models.CharField(blank=True, choices=[('m', 'Gemeld'), ('i', 'In afwachting van behandeling'), ('b', 'In behandeling'), ('o', 'Afgehandeld')], default='m', help_text='Melding status', max_length=1)),
                ('extern', models.BooleanField(default=False, help_text='Wel of niet status extern weergeven')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('extra_properties', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name_plural': 'States',
                'get_latest_by': 'datetime',
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='signals.Status'),
        ),
    ]
