# Generated by Django 2.0.6 on 2018-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='text_extra',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='status',
            name='text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
