# Generated by Django 2.1.11 on 2019-09-02 06:40

from django.db import migrations


def add_reports(apps, schema_editor):
    ReportDefinition = apps.get_model('reporting', 'ReportDefinition')
    ReportIndicator = apps.get_model('reporting', 'ReportIndicator')

    # Add one report with all available indicators.
    new_report = ReportDefinition(
        name='Alle wekelijks beschikbare indicatoren',
        description='Alle indicatoren op wekelijkse basis',
        interval='WEEK',
        category='CATEGORY_SUB',
        area='AREA_ALL',
    )
    new_report.save()

    # Add all indicators
    for indicator_code in [
                "CATEGORIE_NAAM",
                'N_MELDING_GESLOT',
                'N_MELDING_NIEUW',
                'N_MELDING_OPEN',
                'P_MELDING_TEVREDEN',
            ]:
        new_indicator = ReportIndicator(
            report=new_report,
            code=indicator_code,
        )
        new_indicator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_reports)
    ]
