# Generated by Django 2.2.13 on 2020-09-29 10:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_add_dro_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTDO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(max_length=255)),
                ('main_slug', models.CharField(max_length=255)),
                ('sub_slug', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'signals_ext_tdo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='horecacsvexport',
            options={'ordering': ('-isoyear', '-isoweek', '-created_at')},
        ),
    ]
