# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Gemeente Amsterdam
# Generated by Django 3.2.13 on 2022-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_log_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
