# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Gemeente Amsterdam
# Generated by Django 3.2.13 on 2022-07-13 08:41
import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0162_signal_user_HISTORY'),
        ('history', '0004_migrate_change_log_to_history_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='history_log', to='signals.signal'),
        ),
    ]
