# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.20 on 2023-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20220928_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardanswer',
            name='open_answer',
            field=models.BooleanField(default=False,
                                      help_text='Als deze optie is aangevinkt, '
                                                'dan wordt er een open antwoord'
                                                ' verwacht van de melder en is '
                                                'de opgegeven text een default '
                                                'waarde.'),
        ),
    ]
