# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2023 Gemeente Amsterdam
# Generated by Django 3.2.20 on 2023-07-12 12:46

from django.db import migrations, models

import signals.apps.signals.tokens.token_generator


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_standardanswer_open_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='token',
            field=models.CharField(default=signals.apps.signals.tokens.token_generator.TokenGenerator(),
                                   max_length=120,
                                   primary_key=True,
                                   serialize=False),
        ),
    ]
