# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2025 Gemeente Amsterdam
# Generated by Django 4.2.20 on 2025-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_alter_feedback_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardanswer',
            name='open_answer',
            field=models.BooleanField(
                default=False,
                help_text='Als deze optie is aangevinkt, dan wordt een open antwoord verwacht van de melder en is de '
                          'opgegeven tekst een default waarde. De melding krijgt bij deze optie automatisch de status '
                          'verzoek tot heropenen.'
            ),
        ),
        migrations.AlterField(
            model_name='standardanswer',
            name='reopens_when_unhappy',
            field=models.BooleanField(
                default=False,
                help_text='Als deze optie is aangevinkt, krijgt de melding de status verzoek tot heropenen. Let op, '
                          'bij een "open answer" krijgt de melding automatisch de status verzoek tot heropenen.'
            ),
        ),
        migrations.AlterField(
            model_name='standardanswertopic',
            name='order',
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text='De volgorde van de antwoorden onderwerpen voor het KTO proces.',
                null=True
            ),
        ),
    ]
