# Generated by Django 2.2.6 on 2019-10-16 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_blank_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING,
                                       related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
