# Generated by Django 2.2.6 on 2019-11-06 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191016_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(to='signals.Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING,
                                       related_name='profile',
                                       to=settings.AUTH_USER_MODEL,
                                       verbose_name='profile'),
        ),
    ]
