# Generated by Django 2.2.6 on 2019-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191106_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, to='signals.Department'),
        ),
    ]
