# Generated by Django 2.2.9 on 2020-01-20 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191113_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(
                blank=True,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(
                to='signals.Department'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
                verbose_name='profile'
            ),
        ),
    ]
