# Generated by Django 2.2.13 on 2020-12-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0132_migrate_users_signaluser_data'),
        ('users', '0007_signaluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignalUser',
        ),
    ]
