# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2020 - 2021 Vereniging van Nederlandse Gemeenten, Gemeente Amsterdam
# Generated by Django 2.2.13 on 2020-12-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0131_signaluser'),
        ('users', '0007_signaluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignalUser',
        ),
    ]
