# Generated by Django 3.2.15 on 2022-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_signaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_on_assigment_to_department',
            field=models.BooleanField(default=False, verbose_name='Send e-mail notification when a Signal is assigned to the department of the user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_on_assigment_to_user',
            field=models.BooleanField(default=False, verbose_name='Send e-mail notification when a Signal is assigned to the user'),
        ),
    ]
