# Generated by Django 3.2.15 on 2022-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_signaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_on_department_assignment',
            field=models.BooleanField(default=False, verbose_name='Stuur mij een e-mail als een melding aan mijn afdeling is toegewezen'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_on_user_assignment',
            field=models.BooleanField(default=False, verbose_name='Stuur mij een e-mail als een melding aan mij is toegewezen'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(related_name='department_profiles', to='signals.Department'),
        ),
    ]
