# Generated by Django 4.2.11 on 2024-09-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('middle_model', models.FileField(max_length=255, upload_to='classification_models/middle/%Y/%m/%d/')),
                ('middle_sub_model', models.FileField(max_length=255, upload_to='classification_models/middle_sub/%Y/%m/%d/')),
            ],
        ),
    ]
