# Generated by Django 4.2.11 on 2024-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_classifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='classifier',
            name='precision',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='classifier',
            name='recall',
            field=models.FloatField(default=0),
        ),
    ]
