# Generated by Django 4.2.15 on 2024-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_remove_classifier_middle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='main_model',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='classification_models/main/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='sub_model',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='classification_models/main_sub/%Y/%m/%d/'),
        ),
    ]
