# Generated by Django 4.2.19 on 2025-05-15 16:15

from django.db import migrations, models
import signals.apps.classification.utils


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0006_classifier_training_error_classifier_training_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='main_confusion_matrix',
            field=models.FileField(blank=True, max_length=255, null=True, storage=signals.apps.classification.utils._get_storage_backend, upload_to='classification_models/main_confusion_matrix/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='sub_confusion_matrix',
            field=models.FileField(blank=True, max_length=255, null=True, storage=signals.apps.classification.utils._get_storage_backend, upload_to='classification_models/sub_confusion_matrix/%Y/%m/%d/'),
        ),
    ]
