# Generated by Django 2.2.13 on 2020-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(
                    choices=[('signal_created', 'Send mail signal created'),
                             ('signal_status_changed_afgehandeld', 'Send mail signal handled'),
                             ('signal_status_changed_ingepland', 'Send mail signal scheduled'),
                             ('signal_status_changed_heropend', 'Send mail signal reopened'),
                             ('signal_status_changed_optional', 'Send mail optional')],
                    db_index=True,
                    max_length=100
                )),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'E-mail template',
                'verbose_name_plural': 'E-mail templates',
            },
        ),
    ]
