# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2022 Vereniging van Nederlandse Gemeenten
"""
These tests check the contents of PDFs generated byt the PDFSummaryService.
We do not want to parse PDFs, instead we look at the content of the intermediate
HTML.
"""
from django.test import TestCase

from signals.apps.services.domain.pdf_summary import PDFSummaryService
from signals.apps.signals.factories import SignalFactoryValidLocation
from signals.apps.users.factories import SuperUserFactory


class TestPDFSummaryService(TestCase):
    def setUp(self):
        self.signal = SignalFactoryValidLocation.create()
        self.user = SuperUserFactory.create()

    def test_trivial(self):
        PDFSummaryService._get_html(self.signal, self.user)

    def test_get_pdf(self):
        pdf = PDFSummaryService._get_html(self.signal, self.user)
        assert len(pdf)
