name: CI
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: docker-compose -f docker-compose.test.yml build

      - name: pytest
        run: docker-compose -f docker-compose.test.yml run api pytest -n 4 --cov=signals --cov-report=term --cov-report=html:/tmp/test/htmlcov --no-cov-on-fail --tb=short

      - name: flake8
        run: docker-compose -f docker-compose.test.yml run api flake8 signals

      - name: isort
        run: docker-compose -f docker-compose.test.yml run api isort --diff --check-only signals tests

      - name: spdx
        run: docker-compose -f docker-compose.test.yml run api python check_spdx.py .

      - name: mypy
        run: docker-compose -f docker-compose.test.yml run api bash -c "mypy signals | mypy-baseline filter"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: /tmp/test/htmlcov/
