name: CI
on: [push, pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-18.04

    services:
      database:
        image: amsterdam/postgres11
        env:
          POSTGRES_USER: signals
          POSTGRES_PASSWORD: insecure
          POSTGRES_DB: signals

        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Cache pip modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install geospatial libraries # https://docs.djangoproject.com/en/3.0/ref/contrib/gis/install/geolibs/
        run: sudo apt update && sudo apt install binutils libproj-dev gdal-bin graphviz

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: insecure
          DATABASE_HOST_OVERRIDE: localhost
          DJANGO_SETTINGS_MODULE: signals.settings
          SITE_DOMAIN: localhost:8000
          FRONTEND_URL: http://dummy_link
          ALLOWED_HOSTS: '*'
          CORS_ALLOW_ALL_ORIGINS: True
          TEST_JWKS: True
          SIGNALS_AUTH_ALWAYS_OK: True
          TEST_LOGIN: signals.admin@example.com
          SECURE_SSL_REDIRECT: False
          SESSION_COOKIE_SECURE: False
          CSRF_COOKIE_SECURE: False
          CELERY_TASK_ALWAYS_EAGER: True
          EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
          SYSTEM_MAIL_FEEDBACK_RECEIVED_ENABLED: True
          REPORTER_MAIL_HANDLED_NEGATIVE_CONTACT_ENABLED: True
          SIGNAL_HISTORY_LOG_ENABLED: True
        run: |
          cd api/app
          tox

      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: /tmp/test/htmlcov/
