name: CI
on: [push, pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: amsterdam/postgres11
        env:
          POSTGRES_USER: signals
          POSTGRES_PASSWORD: insecure
          POSTGRES_DB: signals
        ports: ['5409:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Cache pip modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install geospatial libraries # https://docs.djangoproject.com/en/3.0/ref/contrib/gis/install/geolibs/
        run: sudo apt install binutils libproj-dev gdal-bin

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run tests
        run: |
          cd api/app
          tox

      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: /tmp/test/htmlcov/
