name: Test

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  container-job:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1
    - run: api/deploy/test/test.sh
